services:
  - type: web
    name: sistema-ugel-backend
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: sistema-ugel-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: https://sistema-ugel-frontend.vercel.app

databases:
  - name: sistema-ugel-db
    databaseName: ugel_db
    user: ugel_user
    region: oregon
